# Generated by Django 2.0.5 on 2018-05-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Zip',
            new_name='zip',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='CompanyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Web',
            new_name='web',
        ),
    ]
