# Generated by Django 2.0.5 on 2018-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20180513_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Age',
            new_name='age',
        ),
    ]
