# Generated by Django 2.0.5 on 2018-05-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20180516_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
